"""Added meme_stats field to the Student

Revision ID: 11562bffc422
Revises: 6d34bc824083
Create Date: 2024-09-01 20:30:43.439939

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "11562bffc422"
down_revision = "6d34bc824083"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("meme_stats", sqlmodel.AutoString(), nullable=True))
    op.execute("UPDATE students SET meme_stats = '{}'")
    op.alter_column("students", "meme_stats", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "meme_stats")
    # ### end Alembic commands ###
