"""Added bonuses_last_visited field to Student

Revision ID: 1540ca48ca5b
Revises: 16299c81bfd0
Create Date: 2024-09-12 13:27:00.531125

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1540ca48ca5b"
down_revision = "16299c81bfd0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("bonuses_last_visited", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "bonuses_last_visited")
    # ### end Alembic commands ###
