"""Added unique constraint to student_challenges and field in products and student_products

Revision ID: 16299c81bfd0
Revises: fcabcb751690
Create Date: 2024-09-11 15:35:56.125090

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16299c81bfd0'
down_revision = 'fcabcb751690'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sqlmodel.AutoString(), nullable=True))
    op.create_unique_constraint('uq_student_challenge', 'student_challenges', ['student_id', 'challenge_id'])
    op.add_column('student_products', sa.Column('added_by', sqlmodel.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_products', 'added_by')
    op.drop_constraint('uq_student_challenge', 'student_challenges', type_='unique')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###