"""Added table 'badges'

Revision ID: 485a84572e13
Revises: 1540ca48ca5b
Create Date: 2024-10-07 22:15:42.545191

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "485a84572e13"
down_revision = "1540ca48ca5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("badge_type", sqlmodel.AutoString(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("student_name", sqlmodel.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("badges")
    # ### end Alembic commands ###
