"""Add last_login to Student and StudentDB models

Revision ID: 6d34bc824083
Revises: 7a7a5290e541
Create Date: 2024-08-29 10:49:16.851584

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6d34bc824083"
down_revision = "7a7a5290e541"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("last_login", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "last_login")
    # ### end Alembic commands ###
