"""Added profession to challenges table

Revision ID: fcabcb751690
Revises: 11562bffc422
Create Date: 2024-09-09 15:38:14.058613

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fcabcb751690"
down_revision = "11562bffc422"
branch_labels = None
depends_on = None


def upgrade() -> None:
    professionenumwithall = sa.Enum("PD", "DA", "GD", "WD", "QA", "JD", "IM", "PM", "ALL", name="professionenumwithall")
    professionenumwithall.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenges", sa.Column("profession", professionenumwithall, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenges", "profession")
    # ### end Alembic commands ###

    professionenumwithall = sa.Enum("PD", "DA", "GD", "WD", "QA", "JD", "IM", "PM", "ALL", name="professionenumwithall")
    professionenumwithall.drop(op.get_bind())
